//package com.javalearning.demo1.complex_pojo.mapper;
//
//import com.javalearning.demo1.complex_pojo.bean.News;
//import com.javalearning.demo1.complex_pojo.bean.NewsExample;
//import java.util.List;
//import org.apache.ibatis.annotations.Param;
//
//public interface NewsMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    long countByExample(NewsExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    int deleteByExample(NewsExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    int insert(News record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    int insertSelective(News record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    List<News> selectByExampleWithBLOBs(NewsExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    List<News> selectByExample(NewsExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    int updateByExampleWithBLOBs(@Param("record") News record, @Param("example") NewsExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table news
//     *
//     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
//     */
//    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);
//}