package com.javalearning.demo.complex_pojo.bean;

import java.io.Serializable;

public class News implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.data
     *
     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
     */
    private byte[] data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.data
     *
     * @return the value of news.data
     *
     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.data
     *
     * @param data the value for news.data
     *
     * @mbg.generated Mon Mar 09 13:32:01 CST 2020
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}